# Generated by Django 2.2 on 2020-07-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_auto_20200702_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
